// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:habit_flow/hive/hive_adapters.dart';
import 'package:hive_ce/hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
  }
}
